# File: run.sh
# Creator : ruihq <ruihq.gh@gmail.com>
# Date : Feb 25 2023

name: Test code

on: 
   workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run shell script
      run: |
        chmod +x run.sh
        ./run.sh

